# SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD AS B, USED_GOODS_USER AS U
# WHERE (U.USER_ID, B.PRICE) IN (SELECT U.USER_ID, B.PRICE
#                                 FROM USED_GOODS_BOARD AS B, USED_GOODS_USER AS U
#                                 WHERE B.STATUS = 'DONE'
#                                 GROUP BY U.USER_ID
#                                 HAVING SUM(B.PRICE) >= 700000);
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B, USED_GOODS_USER AS U
WHERE U.USER_ID = B.WRITER_ID AND B.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(B.PRICE) ASC;

# SELECT * FROM USED_GOODS_BOARD;